# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zaer
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#2025-02-18T15:42:39.378+08:00  WARN 18576 --- [zaer] [  restartedMain] .s.s.UserDetailsServiceAutoConfiguration :
#
#Using generated security password: 2b4d8289-3d71-41ee-a18b-48ea536f5875
#
#This generated password is for development use only. Your security configuration must be updated before running your application in production.