spring:
  application:
    name: redisjava
  data:
    redis:
      host: localhost
      port: 6379
      password:
  datasource:
    url: jdbc:mysql://localhost:3306/zaer
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

